-- Disable Row Level Security on all BRAHMO tables
-- Run this in Supabase SQL Editor

ALTER TABLE organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE hierarchy_levels DISABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_nodes DISABLE ROW LEVEL SECURITY;
ALTER TABLE edges DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE pulse_alerts DISABLE ROW LEVEL SECURITY;
